inputs:
  AWS_ACCESS_KEY_ID:
    description: "AWS KEY ID"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS SECRET KEY"
    required: true

runs:
  using: "composite"
  steps:
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1